-- 1. Invite Codes Table
CREATE TABLE IF NOT EXISTS public.invite_codes (
    code text PRIMARY KEY,
    event_name text NOT NULL,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.invite_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.invite_codes FOR SELECT USING (true);


-- 2. Guests Table
CREATE TABLE IF NOT EXISTS public.guests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    phone text,
    invite_code text REFERENCES public.invite_codes(code) ON DELETE SET NULL,
    registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login timestamp with time zone
);

ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.guests FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.guests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.guests FOR UPDATE USING (true);


-- 3. Photos Table
CREATE TABLE IF NOT EXISTS public.photos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drive_path text UNIQUE NOT NULL,
    is_common boolean DEFAULT false,
    face_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.photos FOR SELECT USING (true);
CREATE POLICY "Allow public upsert" ON public.photos FOR ALL USING (true);


-- 4. Guest Photos (Mapping Table)
CREATE TABLE IF NOT EXISTS public.guest_photos (
    guest_id uuid REFERENCES public.guests(id) ON DELETE CASCADE,
    photo_id bigint REFERENCES public.photos(id) ON DELETE CASCADE,
    PRIMARY KEY (guest_id, photo_id)
);

ALTER TABLE public.guest_photos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.guest_photos FOR SELECT USING (true);
CREATE POLICY "Allow public upsert" ON public.guest_photos FOR ALL USING (true);


-- 5. Download Sessions Table
CREATE TABLE IF NOT EXISTS public.download_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    guest_id uuid REFERENCES public.guests(id) ON DELETE CASCADE,
    status text DEFAULT 'pending'::text NOT NULL,
    photo_count integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.download_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.download_sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.download_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.download_sessions FOR UPDATE USING (true);


-- 6. Insert Mock Invite Code for Testing
INSERT INTO public.invite_codes (code, event_name, active)
VALUES ('WEDDING2024', 'Mahima & Saurav Wedding', true)
ON CONFLICT (code) DO UPDATE SET active = true;
